### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by yxWisdom** [apple55bc/bd-chat-2020#1]
请问是否能分享一下该比赛任务的数据集啊，比赛结束后好像下不了了，感谢！

**Comment by apple55bc** [comment]
可以用这篇论文里的数据集：
https://arxiv.org/pdf/2005.03954.pdf

**Comment by yxWisdom** [comment]
论文中的github链接失效了..

**Comment by apple55bc** [comment]
数据集有保密协议，等等github吧

**Comment by yinyang472** [comment]
想问一下 您找到数据集了么  能私我一份么 qq：289475058

**Comment by apple55bc** [comment]
> 想问一下 您找到数据集了么 能私我一份么 qq：289475058

已发送了

**Comment by DukeKevin** [comment]
可以给我发一份数据集吗？  328710927@qq.com
谢谢大佬
