### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by zzcceeyy** [apple55bc/bd-chat-2020#10]
你好，我在运行data_deal/pre_trans.py的时候，报错了 typeerror:expected string or bytes-like object
我想问下test的格式，我这是千言比赛中的DuRecDial中的测试集。是格式的问题么
![9aa1a1c3eef2836d8f9f2eca23e132](https://user-images.githubusercontent.com/88641930/132095772-dd888e40-f8a0-468d-87fe-ecf13067d722.jpg)

**Comment by apple55bc** [comment]
格式问题。
test格式应该是这样，训练集格式也是类似：

`{"goal": "[1] 问答 ( User 主动 按 『 参考 知识 』   问   『 周迅 』   的 信息 ， Bot 回答 ， User 满意 并 好评 )--> ...... --> [3] 电影 推荐 ( Bot 主动 ， Bot 使用   『 李米的猜想 』   的 某个 评论 当做 推荐 理由 来 推荐   『 李米的猜想 』 ， User 先问 电影 『 国家 地区 、 导演 、 类型 、 主演 、 口碑 、 评分 』 中 的 一个 或 多个 ， Bot 回答 ， 最终 User 接受 ) --> [4] 再见", "knowledge": [["周迅", "主演", "李米的猜想"], ["李米的猜想", "评论", "疯狂 的 女人 疯狂 地爱 着 一个 男人"], ["李米的猜想", "评论", "故事 可以 ， 配乐 更棒 。"], ["李米的猜想", "评论", "周迅 的 灵性 在 这部 片子 里 展露 无遗 。"], ["李米的猜想", "评论", "放肆 的 哭 ， 为 爱 付出"], ["李米的猜想", "评论", "@ 在 上海 的 徐 锰 _ XM"], ["李米的猜想", "国家地区", "中国"], ["李米的猜想", "导演", "曹 保平"], ["李米的猜想", "类型", "爱情   剧情   犯罪"], ["李米的猜想", "主演", "周迅   邓超   张涵予   王宝强"], ["李米的猜想", "口碑", "口碑 还好"], ["李米的猜想", "评分", "7.3"], ["周迅", "获奖", "中国 电影 金鸡奖 _ 最佳 女主角"], ["周迅", "获奖", "香港电影 金像奖 _ 金像奖 - 最佳 原创 电影 歌曲 奖"], ["周迅", "获奖", "台湾 电影 金马奖 _ 金马奖 - 最佳 女 主角奖"], ["周迅", "获奖", "亚洲 电影 大奖 _ 最佳 女演员"], ["周迅", "获奖", "华语 电影 传媒 大奖 _ 最佳 女演员"], ["周迅", "出生地", "中国   浙江   衢州"], ["周迅", "体重", "41kg"], ["周迅", "成就", "香港电影 金像奖 最佳 女主角"], ["周迅", "成就", "亚洲 电影 大奖 最佳 女主角"], ["周迅", "成就", "香港电影 金紫荆 奖 最佳 女主角"], ["周迅", "成就", "台湾 电影 金马奖 最佳 女主角"], ["周迅", "成就", "中国 电视 金鹰奖 最 受欢迎 女演员"], ["周迅", "评论", "就是 喜欢 你 。 演技 超好 ， 脸蛋 真 漂漂 。"], ["周迅", "评论", "迄今为止 演艺圈 最有 灵性 的 内地 女演员"], ["周迅", "评论", "# 印象 周迅 # 好 演员 ， 支持 ！ ！ ！ ！"], ["周迅", "评论", "最 喜欢 有 独特 气质 的 人 了"], ["周迅", "评论", "她 是 真正 的 为 演艺 而生 。 前 无 借鉴 ， 后无来者 。"], ["周迅", "生日", "1974 - 10 - 18"], ["周迅", "身高", "161cm"], ["周迅", "星座", "天秤座"], ["周迅", "血型", "O型"], ["李米的猜想", "评论", "《 李米的猜想 》 上演 的 仍旧 是 一出 关于 等待 、 关于 爱 的 故事 ， 不过 片中 的 爱 浪漫 得 让 人 笑 中 带泪 。 周迅 在 这部 影片 中 奉献 出 了 极富 投入 的 激情 与 诚意 ， 把 观众 带入 了 那场 “ 死 了 都 要 爱 ” 的 情境 里 ， 让 人生 出 许多 关于 城市 、 关于 爱 、 关于 得失 的 感慨 。"], ["李米的猜想", "评论", ""], ["李米的猜想", "评论", "导演 在 镜头 的 衔接 、 情节 的 设计 上用 了 很多 心思 ， 故意 造成 一种 前言不搭后语 的 悬念 ， 然后 通过 情节 内容 的 不断丰富 ， 将 前后 串连 起来 ， 不到 最后 ， 观众 都 不 知道 谜底 是 什么 ， 这样 的 手法 算得 上 高明 。 周迅 的 表演 得到 了 部分 观众 的 肯定 ， 虽然 片中 她 饰演 的 李米 既 粗鲁 又 憔悴 ， 没有 以往 周迅 那种 精灵 般的 感觉 ， 但 在 她 为 爱情 崩溃 、 哭泣 和 微笑 时 ， 依然 可以 看到 她 任性 的 天真 。"], ["李米的猜想", "评论", "《 李米的猜想 》 用 爱情 这个 永恒 被 关注 的 话题 给 观众 讲述 了 一个 题材 边缘 的 故事 。 导演 曹 保平 运用 的 明星 策略 也 使得 这部 文艺片 性质 的 电影 获得 了 更 多 在 大众 面前 曝光 的 机会 。 与 以往 的 文艺片 相比 ， 《 李米的猜想 》 使用 了 更 多 的 明星 ， 在 这 基础 下 ， 曹 保平 的 这部 电影 获得 了 不俗 的 口碑 和 声望 ， 也 让 一个 题材 边缘 的 故事 获得 了 在 主流 院线 上线 的 机会 。 在 国内 的 电影票房 市场 上 ， 小 成本 电影 只能 占据 很小 的 份额 ， 而 《 李米的猜想 》 的 出现 ， 则 为 小 成本 电影 提供 了 一个 一线 明星 嫁接 小 成本 文艺片 的 成功 范例 。"]], "situation": "聊天 时间 : 晚上 20 : 00 ， 在 家里", "history": ["[1] 周迅 的 星座 是 什么 ？", "周迅 是 天秤座 。", "你 真棒 ！ 知道 的 真多 。", "[2] 我 还 知道 周迅 可是 亚洲 电影 大奖 最佳 女主角 呢 ！", "周迅 可是 我 的 偶像 ， 她 的 演技 超好 。"], "user_profile": {"姓名": "杨丽菲", "性别": "女", "居住地": "深圳", "年龄区间": "18-25", "职业状态": "学生", "喜欢 的 明星": ["周迅"], "喜欢 的 电影": ["苏州河"], "喜欢 的 poi": ["宅宅湘菜"], "同意 的 美食": " 剁椒鱼头", "同意 的 新闻": " 周迅 的新闻", "拒绝": ["音乐"], "接受 的 电影": ["巴尔扎克和小裁缝", "香港有个好莱坞"], "没有接受 的 电影": ["鸳鸯蝴蝶"]}}
{"goal": "[1] 问答 ( User 主动 按 『 参考 知识 』   问   『 周迅 』   的 信息 ， Bot 回答 ， User 满意 并 好评 )--> ...... --> [3] 电影 推荐 ( Bot 主动 ， Bot 使用   『 李米的猜想 』   的 某个 评论 当做 推荐 理由 来 推荐   『 李米的猜想 』 ， User 先问 电影 『 国家 地区 、 导演 、 类型 、 主演 、 口碑 、 评分 』 中 的 一个 或 多个 ， Bot 回答 ， 最终 User 接受 ) --> [4] 再见", "knowledge": [["周迅", "主演", "李米的猜想"], ["李米的猜想", "评论", "疯狂 的 女人 疯狂 地爱 着 一个 男人"], ["李米的猜想", "评论", "故事 可以 ， 配乐 更棒 。"], ["李米的猜想", "评论", "周迅 的 灵性 在 这部 片子 里 展露 无遗 。"], ["李米的猜想", "评论", "放肆 的 哭 ， 为 爱 付出"], ["李米的猜想", "评论", "@ 在 上海 的 徐 锰 _ XM"], ["李米的猜想", "国家地区", "中国"], ["李米的猜想", "导演", "曹 保平"], ["李米的猜想", "类型", "爱情   剧情   犯罪"], ["李米的猜想", "主演", "周迅   邓超   张涵予   王宝强"], ["李米的猜想", "口碑", "口碑 还好"], ["李米的猜想", "评分", "7.3"], ["周迅", "获奖", "中国 电影 金鸡奖 _ 最佳 女主角"], ["周迅", "获奖", "香港电影 金像奖 _ 金像奖 - 最佳 原创 电影 歌曲 奖"], ["周迅", "获奖", "台湾 电影 金马奖 _ 金马奖 - 最佳 女 主角奖"], ["周迅", "获奖", "亚洲 电影 大奖 _ 最佳 女演员"], ["周迅", "获奖", "华语 电影 传媒 大奖 _ 最佳 女演员"], ["周迅", "出生地", "中国   浙江   衢州"], ["周迅", "体重", "41kg"], ["周迅", "成就", "香港电影 金像奖 最佳 女主角"], ["周迅", "成就", "亚洲 电影 大奖 最佳 女主角"], ["周迅", "成就", "香港电影 金紫荆 奖 最佳 女主角"], ["周迅", "成就", "台湾 电影 金马奖 最佳 女主角"], ["周迅", "成就", "中国 电视 金鹰奖 最 受欢迎 女演员"], ["周迅", "评论", "就是 喜欢 你 。 演技 超好 ， 脸蛋 真 漂漂 。"], ["周迅", "评论", "迄今为止 演艺圈 最有 灵性 的 内地 女演员"], ["周迅", "评论", "# 印象 周迅 # 好 演员 ， 支持 ！ ！ ！ ！"], ["周迅", "评论", "最 喜欢 有 独特 气质 的 人 了"], ["周迅", "评论", "她 是 真正 的 为 演艺 而生 。 前 无 借鉴 ， 后无来者 。"], ["周迅", "生日", "1974 - 10 - 18"], ["周迅", "身高", "161cm"], ["周迅", "星座", "天秤座"], ["周迅", "血型", "O型"], ["李米的猜想", "评论", "《 李米的猜想 》 上演 的 仍旧 是 一出 关于 等待 、 关于 爱 的 故事 ， 不过 片中 的 爱 浪漫 得 让 人 笑 中 带泪 。 周迅 在 这部 影片 中 奉献 出 了 极富 投入 的 激情 与 诚意 ， 把 观众 带入 了 那场 “ 死 了 都 要 爱 ” 的 情境 里 ， 让 人生 出 许多 关于 城市 、 关于 爱 、 关于 得失 的 感慨 。"], ["李米的猜想", "评论", ""], ["李米的猜想", "评论", "导演 在 镜头 的 衔接 、 情节 的 设计 上用 了 很多 心思 ， 故意 造成 一种 前言不搭后语 的 悬念 ， 然后 通过 情节 内容 的 不断丰富 ， 将 前后 串连 起来 ， 不到 最后 ， 观众 都 不 知道 谜底 是 什么 ， 这样 的 手法 算得 上 高明 。 周迅 的 表演 得到 了 部分 观众 的 肯定 ， 虽然 片中 她 饰演 的 李米 既 粗鲁 又 憔悴 ， 没有 以往 周迅 那种 精灵 般的 感觉 ， 但 在 她 为 爱情 崩溃 、 哭泣 和 微笑 时 ， 依然 可以 看到 她 任性 的 天真 。"], ["李米的猜想", "评论", "《 李米的猜想 》 用 爱情 这个 永恒 被 关注 的 话题 给 观众 讲述 了 一个 题材 边缘 的 故事 。 导演 曹 保平 运用 的 明星 策略 也 使得 这部 文艺片 性质 的 电影 获得 了 更 多 在 大众 面前 曝光 的 机会 。 与 以往 的 文艺片 相比 ， 《 李米的猜想 》 使用 了 更 多 的 明星 ， 在 这 基础 下 ， 曹 保平 的 这部 电影 获得 了 不俗 的 口碑 和 声望 ， 也 让 一个 题材 边缘 的 故事 获得 了 在 主流 院线 上线 的 机会 。 在 国内 的 电影票房 市场 上 ， 小 成本 电影 只能 占据 很小 的 份额 ， 而 《 李米的猜想 》 的 出现 ， 则 为 小 成本 电影 提供 了 一个 一线 明星 嫁接 小 成本 文艺片 的 成功 范例 。"]], "situation": "聊天 时间 : 晚上 20 : 00 ， 在 家里", "history": ["[1] 周迅 的 星座 是 什么 ？", "周迅 是 天秤座 。", "你 真棒 ！ 知道 的 真多 。", "[2] 我 还 知道 周迅 可是 亚洲 电影 大奖 最佳 女主角 呢 ！", "周迅 可是 我 的 偶像 ， 她 的 演技 超好 。", "她 是 真正 的 为 演艺 而生 ， 而且 还 获得 过 华语 电影 传媒 大奖 最佳 女演员 。", "我 非常 喜欢 她 演 的 电影 。", "[3] 那 正好 了 ， 推荐 你 看看 周迅 主演 的 『 李米的猜想 』 ， 周迅 在 这部 影片 中 奉献 出 了 极富 投入 的 激情 与 诚意 ， 把 观众 带入 了 那场 “ 死 了 都 要 爱 ” 的 情境 里 ， 让 人生 出 许多 关于 城市 、 关于 爱 、 关于 得失 的 感慨 。", "这部 电影 的 口碑 怎么样 ？"], "user_profile": {"姓名": "杨丽菲", "性别": "女", "居住地": "深圳", "年龄区间": "18-25", "职业状态": "学生", "喜欢 的 明星": ["周迅"], "喜欢 的 电影": ["苏州河"], "喜欢 的 poi": ["宅宅湘菜"], "同意 的 美食": " 剁椒鱼头", "同意 的 新闻": " 周迅 的新闻", "拒绝": ["音乐"], "接受 的 电影": ["巴尔扎克和小裁缝", "香港有个好莱坞"], "没有接受 的 电影": ["鸳鸯蝴蝶"]}}
{"goal": "[1] 问答 ( User 主动 按 『 参考 知识 』   问   『 周迅 』   的 信息 ， Bot 回答 ， User 满意 并 好评 )--> ...... --> [3] 电影 推荐 ( Bot 主动 ， Bot 使用   『 李米的猜想 』   的 某个 评论 当做 推荐 理由 来 推荐   『 李米的猜想 』 ， User 先问 电影 『 国家 地区 、 导演 、 类型 、 主演 、 口碑 、 评分 』 中 的 一个 或 多个 ， Bot 回答 ， 最终 User 接受 ) --> [4] 再见", "knowledge": [["周迅", "主演", "李米的猜想"], ["李米的猜想", "评论", "疯狂 的 女人 疯狂 地爱 着 一个 男人"], ["李米的猜想", "评论", "故事 可以 ， 配乐 更棒 。"], ["李米的猜想", "评论", "周迅 的 灵性 在 这部 片子 里 展露 无遗 。"], ["李米的猜想", "评论", "放肆 的 哭 ， 为 爱 付出"], ["李米的猜想", "评论", "@ 在 上海 的 徐 锰 _ XM"], ["李米的猜想", "国家地区", "中国"], ["李米的猜想", "导演", "曹 保平"], ["李米的猜想", "类型", "爱情   剧情   犯罪"], ["李米的猜想", "主演", "周迅   邓超   张涵予   王宝强"], ["李米的猜想", "口碑", "口碑 还好"], ["李米的猜想", "评分", "7.3"], ["周迅", "获奖", "中国 电影 金鸡奖 _ 最佳 女主角"], ["周迅", "获奖", "香港电影 金像奖 _ 金像奖 - 最佳 原创 电影 歌曲 奖"], ["周迅", "获奖", "台湾 电影 金马奖 _ 金马奖 - 最佳 女 主角奖"], ["周迅", "获奖", "亚洲 电影 大奖 _ 最佳 女演员"], ["周迅", "获奖", "华语 电影 传媒 大奖 _ 最佳 女演员"], ["周迅", "出生地", "中国   浙江   衢州"], ["周迅", "体重", "41kg"], ["周迅", "成就", "香港电影 金像奖 最佳 女主角"], ["周迅", "成就", "亚洲 电影 大奖 最佳 女主角"], ["周迅", "成就", "香港电影 金紫荆 奖 最佳 女主角"], ["周迅", "成就", "台湾 电影 金马奖 最佳 女主角"], ["周迅", "成就", "中国 电视 金鹰奖 最 受欢迎 女演员"], ["周迅", "评论", "就是 喜欢 你 。 演技 超好 ， 脸蛋 真 漂漂 。"], ["周迅", "评论", "迄今为止 演艺圈 最有 灵性 的 内地 女演员"], ["周迅", "评论", "# 印象 周迅 # 好 演员 ， 支持 ！ ！ ！ ！"], ["周迅", "评论", "最 喜欢 有 独特 气质 的 人 了"], ["周迅", "评论", "她 是 真正 的 为 演艺 而生 。 前 无 借鉴 ， 后无来者 。"], ["周迅", "生日", "1974 - 10 - 18"], ["周迅", "身高", "161cm"], ["周迅", "星座", "天秤座"], ["周迅", "血型", "O型"], ["李米的猜想", "评论", "《 李米的猜想 》 上演 的 仍旧 是 一出 关于 等待 、 关于 爱 的 故事 ， 不过 片中 的 爱 浪漫 得 让 人 笑 中 带泪 。 周迅 在 这部 影片 中 奉献 出 了 极富 投入 的 激情 与 诚意 ， 把 观众 带入 了 那场 “ 死 了 都 要 爱 ” 的 情境 里 ， 让 人生 出 许多 关于 城市 、 关于 爱 、 关于 得失 的 感慨 。"], ["李米的猜想", "评论", ""], ["李米的猜想", "评论", "导演 在 镜头 的 衔接 、 情节 的 设计 上用 了 很多 心思 ， 故意 造成 一种 前言不搭后语 的 悬念 ， 然后 通过 情节 内容 的 不断丰富 ， 将 前后 串连 起来 ， 不到 最后 ， 观众 都 不 知道 谜底 是 什么 ， 这样 的 手法 算得 上 高明 。 周迅 的 表演 得到 了 部分 观众 的 肯定 ， 虽然 片中 她 饰演 的 李米 既 粗鲁 又 憔悴 ， 没有 以往 周迅 那种 精灵 般的 感觉 ， 但 在 她 为 爱情 崩溃 、 哭泣 和 微笑 时 ， 依然 可以 看到 她 任性 的 天真 。"], ["李米的猜想", "评论", "《 李米的猜想 》 用 爱情 这个 永恒 被 关注 的 话题 给 观众 讲述 了 一个 题材 边缘 的 故事 。 导演 曹 保平 运用 的 明星 策略 也 使得 这部 文艺片 性质 的 电影 获得 了 更 多 在 大众 面前 曝光 的 机会 。 与 以往 的 文艺片 相比 ， 《 李米的猜想 》 使用 了 更 多 的 明星 ， 在 这 基础 下 ， 曹 保平 的 这部 电影 获得 了 不俗 的 口碑 和 声望 ， 也 让 一个 题材 边缘 的 故事 获得 了 在 主流 院线 上线 的 机会 。 在 国内 的 电影票房 市场 上 ， 小 成本 电影 只能 占据 很小 的 份额 ， 而 《 李米的猜想 》 的 出现 ， 则 为 小 成本 电影 提供 了 一个 一线 明星 嫁接 小 成本 文艺片 的 成功 范例 。"]], "situation": "聊天 时间 : 晚上 20 : 00 ， 在 家里", "history": ["[1] 周迅 的 星座 是 什么 ？", "周迅 是 天秤座 。", "你 真棒 ！ 知道 的 真多 。", "[2] 我 还 知道 周迅 可是 亚洲 电影 大奖 最佳 女主角 呢 ！", "周迅 可是 我 的 偶像 ， 她 的 演技 超好 。", "她 是 真正 的 为 演艺 而生 ， 而且 还 获得 过 华语 电影 传媒 大奖 最佳 女演员 。", "我 非常 喜欢 她 演 的 电影 。", "[3] 那 正好 了 ， 推荐 你 看看 周迅 主演 的 『 李米的猜想 』 ， 周迅 在 这部 影片 中 奉献 出 了 极富 投入 的 激情 与 诚意 ， 把 观众 带入 了 那场 “ 死 了 都 要 爱 ” 的 情境 里 ， 让 人生 出 许多 关于 城市 、 关于 爱 、 关于 得失 的 感慨 。", "这部 电影 的 口碑 怎么样 ？", "口碑 还好 哦 。", "那 我 现在 去 看看 啦 。", "好 的 ， 以后 你 想 看 电影 的 时候 可以 找 我 呦 。", "[4] 下次 再聊 ， 再见 。"], "user_profile": {"姓名": "杨丽菲", "性别": "女", "居住地": "深圳", "年龄区间": "18-25", "职业状态": "学生", "喜欢 的 明星": ["周迅"], "喜欢 的 电影": ["苏州河"], "喜欢 的 poi": ["宅宅湘菜"], "同意 的 美食": " 剁椒鱼头", "同意 的 新闻": " 周迅 的新闻", "拒绝": ["音乐"], "接受 的 电影": ["巴尔扎克和小裁缝", "香港有个好莱坞"], "没有接受 的 电影": ["鸳鸯蝴蝶"]}}
`
