### ISSUE TITLE
请问有答辩文档或者答辩视频链接吗？

### ISSUE THREAD

**Issue by cingtiye** [apple55bc/bd-chat-2020#11]
非常感谢大佬开源方案~
请问有答辩视频或者答辩文档链接吗？
特别想学习大佬的方案~

**Comment by apple55bc** [comment]
有链接，https://zhuanlan.zhihu.com/p/343061563

**Comment by cingtiye** [comment]
你好~请问训练这个模型你用的是cuda10.x还是cuda11.x，发现用cuda11.x好像不能运行。

**Comment by apple55bc** [comment]
tensorflow1.14最高版本。对于的cuda可能是10.x。老版本的tensorflow，如果要用tensorflow2.x （支持更高版本cuda）运行不建议，因为2.0和1.14接口差别很大。

**Comment by cingtiye** [comment]
非常感谢~
晚上用了cuda9.x运行了，但是把保存的文件改成`save_path = join(save_dir, 'trained.tf')`。
不然会报错，ValueError: Unable to create group (name already exists)

再次感谢~
