### ISSUE TITLE
导入预训练模型问题

### ISSUE THREAD

**Issue by jfzhouyoo** [apple55bc/bd-chat-2020#2]
![image](https://user-images.githubusercontent.com/42347225/97134753-3a3d8200-1789-11eb-81be-479216964936.png)
您好，在导入了roberta预训练模型的bert_model(包括checkpoint等文件)之后，运行train_bert_lm.py时出现了上面的错误，想请问您一下这可能是什么原因导致的呢？非常感谢您！

**Comment by apple55bc** [comment]
模型文件格式不对。
去这里下载 
https://github.com/ymcui/Chinese-BERT-wwm
RoBERTa-wwm-ext, Chinese

**Comment by jfzhouyoo** [comment]
好的，谢谢您！
