### ISSUE TITLE
关于predict_lm的问题

### ISSUE THREAD

**Issue by ha-lins** [apple55bc/bd-chat-2020#3]
Hi @apple55bc,

感谢您的代码分享！

（1）我在训练后运行测试代码predict_lm.py的时候，遇到了这个报错：
![image](https://user-images.githubusercontent.com/22448743/98623914-a69eb080-2347-11eb-9f65-c7ce8a72b1b0.png)

这似乎是模型训练、保存的时候引发的问题，请问您有什么相关的建议吗？谢谢！
 
（2）我在训练的时候也遇到一个报错信息：
![image](https://user-images.githubusercontent.com/22448743/98624107-0b5a0b00-2348-11eb-9d47-fecf105e3e17.png)

这个原因似乎是test文件造成的，我用的下面这个比赛提供的数据集，只有一个test文件，但是在您的config里，需要test_1和test_2，请问他们的格式是一样的吗？我猜测可能是同一个test划分出来的。

数据集：https://www.datafountain.cn/competitions/470/datasets
预训练模型：chinese_roberta_wwm_ext_L-12_H-768_A-12

**Comment by apple55bc** [comment]
上面两个是不是h5py版本的问题。之前遇过类似的卸了h5py和keras，重装了keras好了

百度数据集两个文件格式一样的。但是和前言发布的数据集，test里的goal的格式好像不一样，一个是 str，一个是list  [[str]]

**Comment by ha-lins** [comment]
是的，您说的没错。第一个问题training意外中断造成的，我重新完整地train以后，问题就解决了。

我想问下，之前的比赛为什么会有两个test文件呢？您说的格式不同确实会有影响。

谢谢！

**Comment by apple55bc** [comment]
两个test文件格式一样，一个是初赛测试集，一个复赛测试集
