### ISSUE TITLE
SMP2020

### ISSUE THREAD

**Issue by julielin123** [apple55bc/bd-chat-2020#4]
请问会公开SMP2020知识驱动对话方案的代码吗？根据分享的方案进行复现，但是还是有些细节不太清楚，不知道方不方便交流一下。

**Comment by apple55bc** [comment]
KD-Conv不是个人名义参赛，代码不方便公开。有啥细节问题可以直接问吧

**Comment by julielin123** [comment]
好的，谢谢，我有以下几个问题：
**主题提取模型**
1.输入的对话历史有几句？
2.标记对话历史实体的时候，只标记了最后一个subject吗？如果最后一句话谈论到了两个实体应该如何处理？

**三元组筛选**
1.	输入的上文历史有多长?
2.	对输入的history,subject,predicate是否进行裁剪，如果是，是如何裁剪的呢？
3.	Kb中一个subject，一个predicate可能有多个object，是进行了合并吗？
4.     predicate拼接进行预测的方法，和单独对一个predicate做二分类的模型效果有什么差别吗

**生成模型**
使用的预训练模型是公开的吗还是自行训练的？

**领域数据使用**
是单独使用某一领域数据，训练三个模型吗？

**Comment by apple55bc** [comment]
你好，我按照印象回答，某些数字可能有出入。

**主题提取模型**
1.输入的对话历史有几句？
对话历史在训练阶段是随机N句，不超过模型max_len就好。
预测阶段填充最大历史，不超过max_len

2.标记对话历史实体的时候，只标记了最后一个subject吗？如果最后一句话谈论到了两个实体应该如何处理？
原始训练数据中，多数轮数的对话标记了多个实体，但是根据对话上下文、Knowledge中实体关系，最终抽选出了最贴合当前轮对话的实体作为最终的Topic。

**三元组筛选**

1：输入的上文历史有多长?
同主题提取模型，对话历史在训练阶段是随机N句，不超过模型max_len就好。

2：对输入的history,subject,predicate是否进行裁剪，如果是，是如何裁剪的呢？
会有裁剪，subject不裁，predicate随机选取1（真实答案）+N（大概为10左右）不会裁剪，history裁剪到整个position不会超过max_len。

3：predicate拼接进行预测的方法，和单独对一个predicate做二分类的模型效果有什么差别吗
准确率上应该差别不会太大吧，这个没有做对比。最大不同是加速训练和预测效率。

**生成模型**
1：Kb中一个subject，一个predicate可能有多个object，是进行了合并吗？
方案中没有采用合并，训练预测阶段其实会选取2-3个predicate包含的所有object放入模型中，其中训练阶段为1个真实Predicate和若干（2-3）个干扰项。采用合并也许效果更好。

2：使用的预训练模型是公开的吗还是自行训练的？
使用的是哈工大版的roberta-wwm-ext模型，没有自行训练。

3：补充：
PPT方案中应该有个错误，最终生成模型不使用Knowledge和History之间的Mask效果应该更好。

**领域数据使用**
1：是单独使用某一领域数据，训练三个模型吗？
使用了多个领域数据，训练到一个模型中去。

**Comment by julielin123** [comment]
谢谢你的回复，我还有两个问题：
1. decode过程
视频中提到的nucleus sample=4|5，这里是采用了nucleus samling吗？详见https://arxiv.org/pdf/1904.09751.pdf
如果是话，为什么参数会是4\5，而不是p。还是你使用的是top k sampling？
![image](https://user-images.githubusercontent.com/25223871/104732363-154d1f80-5778-11eb-9403-75f9474cbfad.png)
2. 补充提到的attention mask是改成下图形式吗？
![image](https://user-images.githubusercontent.com/25223871/104732680-8ab8f000-5778-11eb-8a88-ddb34abe8b26.png)

**Comment by apple55bc** [comment]
> 谢谢你的回复，我还有两个问题：
> 
> 1. decode过程
>    视频中提到的nucleus sample=4|5，这里是采用了nucleus samling吗？详见https://arxiv.org/pdf/1904.09751.pdf
>    如果是话，为什么参数会是4\5，而不是p。还是你使用的是top k sampling？
>    ![image](https://user-images.githubusercontent.com/25223871/104732363-154d1f80-5778-11eb-9403-75f9474cbfad.png)
> 2. 补充提到的attention mask是改成下图形式吗？
>    ![image](https://user-images.githubusercontent.com/25223871/104732680-8ab8f000-5778-11eb-8a88-ddb34abe8b26.png)

1：decode过程的nucleus sample的1、4是说每次生成N个，然后取最短的那个回复作为最终回复。这个只是个trick，增加测试集的distinct，应该只对这个数据集有效。实际测试集生成内容可能会用大量重复知识，最短回复是尽可能不包含Knowledge的回复（所以测试集分布结合评估方式，可能有点问题）。
2：是这样的Attention Mask

**Comment by ziyantao** [comment]
您好，我想起请问一下，预训练配置文件是自动下载吗还是自己下载，为什么我运行会报错呢
