### ISSUE TITLE
有关预训练模型问题

### ISSUE THREAD

**Issue by ziyantao** [apple55bc/bd-chat-2020#5]
请问一下，在训练过程中是要自己去下载roberta相关预训练模型并放到相应的数据文件下吗？模型不会自动下载是嘛？非常感谢！

**Comment by apple55bc** [comment]
需要自己下载模型文件
https://github.com/ymcui/Chinese-BERT-wwm
从上面地址下载roberta吧。把 bert_model.ckpt 放在data/roberta目录下，其它文件不要覆盖

**Comment by ziyantao** [comment]
好的，我去试试。谢谢您！

**Comment by ziyantao** [comment]
请问是把所有bert_model.ckpt前缀的都放进去么，因为解压出了三个model.ckpt文件，后面带着index，meta后缀什么的

**Comment by ziyantao** [comment]
![image](https://user-images.githubusercontent.com/40757393/116589183-f5b8bc00-a94e-11eb-8474-75c4662e1a22.png)
想问一下这个报错shi zen是怎么回事

**Comment by apple55bc** [comment]
> 请问是把所有bert_model.ckpt前缀的都放进去么，因为解压出了三个model.ckpt文件，后面带着index，meta后缀什么的

三个 model.ckpt 后面带后缀的也放进去，这是tensorflow 存储图结构、参数的文件。其它两个是配置文件和vocab，不要覆盖。

**Comment by apple55bc** [comment]
> ![image](https://user-images.githubusercontent.com/40757393/116589183-f5b8bc00-a94e-11eb-8474-75c4662e1a22.png)
> 想问一下这个报错shi zen是怎么回事

你可能下载的模型文件不太对。你查阅下 bert4keras 项目的加载说明。哈工大版本的可以直接加载

**Comment by ziyantao** [comment]
感谢您的回复，关于模型还有一点疑问，请问是在哪里将bert改成单向注意力的呢

**Comment by ziyantao** [comment]
以及是如何用bert构造自回归模型的呀

**Comment by apple55bc** [comment]
> 以及是如何用bert构造自回归模型的呀

自回归分训练方式和预测。
训练时候需要attention自左向右，每一个token的输出需要是下一个token，这个损失在 bert_lm.py 中的 compile 函数可以看到。
预测时候根据上文逐步预测最后一个token位置所预测的next token。需要查看 bert_lm.py 里的 Response。（需要查阅bert4keras源码）
至于如何改bert为单向注意力，参考 bert_lm.py中的 build_transformer_model 函数的 application='lm' 参数 （需要查阅bert4keras源码）

**Comment by ziyantao** [comment]
> > 以及是如何用bert构造自回归模型的呀
> 
> 自回归分训练方式和预测。
> 训练时候需要attention自左向右，每一个token的输出需要是下一个token，这个损失在 bert_lm.py 中的 compile 函数可以看到。
> 预测时候根据上文逐步预测最后一个token位置所预测的next token。需要查看 bert_lm.py 里的 Response。（需要查阅bert4keras源码）
> 至于如何改bert为单向注意力，参考 bert_lm.py中的 build_transformer_model 函数的 application='lm' 参数 （需要查阅bert4keras源码）

好的，我去研究一下，万分感谢您！！！

**Comment by ziyantao** [comment]
请问predictt_final是最终的预测文件吗，其他的predict文件也要运行吗？另外我看到predic_final中的from_pre_trans参数为False是测试的时候可以不用预处理数据的意思吗，那pretrans这步还有什么用呢？

**Comment by apple55bc** [comment]
> 请问predictt_final是最终的预测文件吗，其他的predict文件也要运行吗？另外我看到predic_final中的from_pre_trans参数为False是测试的时候可以不用预处理数据的意思吗，那pretrans这步还有什么用呢？

都要预处理的，from_pre_trans代表从已经预处理好的文件中读取，实时预测的样本都是未经过预处理的，所以没有预处理好的文件，这个参数就设置为false了
