### ISSUE TITLE
有关OOV的问题

### ISSUE THREAD

**Issue by sf91971684** [apple55bc/bd-chat-2020#6]
hi~ 想请教您一个问题，就是bert的原始词典里不包含'[GOAL]'应该怎么解决呢？感谢您！！！

![image](https://user-images.githubusercontent.com/26037303/116645815-2b8a8e80-a9a9-11eb-8752-c112adcf61e8.png)

**Comment by apple55bc** [comment]
不要覆盖 data/roberta 里的 vocab.txt 和 config

**Comment by sf91971684** [comment]
> 不要覆盖 data/roberta 里的 vocab.txt 和 config

谢谢您～不过词典都变了的话，模型还可以使用原来预训练的模型嘛？因为我印象中预训练的embedding是和词典一致的呀？

**Comment by apple55bc** [comment]
你可以看一下改了哪些vocab就明白了

**Comment by sf91971684** [comment]
再次感谢～～～
