### ISSUE TITLE
关于预测模型的问题

### ISSUE THREAD

**Issue by ziyantao** [apple55bc/bd-chat-2020#7]
作者您好，关于这个模型我有一点疑惑，因为bert是encoder组成的，所以好像没有生成对话的能力，请问您的生成与预测模型是在哪里写的呢？我看了好几个文件都没有找到，迫切希望您的回答，非常感谢！

**Comment by apple55bc** [comment]
给你几个参考吧，这完全是模型基础理解和源码阅读的问题。

https://github.com/bojone/bert4keras/blob/master/examples/basic_language_model_cpm_lm.py  

http://www.360doc.com/content/21/0105/22/7673502_955386606.shtml

https://github.com/apple55bc/bd-chat-2020/issues/5#issuecomment-829925664

**Comment by ziyantao** [comment]
> 给你几个参考吧，这完全是模型基础理解和源码阅读的问题。
> 
> https://github.com/bojone/bert4keras/blob/master/examples/basic_language_model_cpm_lm.py
> 
> http://www.360doc.com/content/21/0105/22/7673502_955386606.shtml
> 
> [#5 (comment)](https://github.com/apple55bc/bd-chat-2020/issues/5#issuecomment-829925664)

我看作者您采用的是lm方法，请问为什么不按照第二篇文章里说的采用seqtoseq的unilm方法呢

**Comment by apple55bc** [comment]
其实也可以使用unilm，只是训练方式得改下，一次只能训练一个Response，因为双向注意力的部分没法做训练，只有单向注意力的可以训练文本生成（因为预测的时候，注意力是单向的，不能未卜先知）
